
title: 王叹之的博客
description: 记录技术与生活 | Crypto
url: https://wangtanzhi6.github.io
locale: zh-CN

remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

paginate: 5
paginate_path: /page:num/

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      toc: true
      toc_sticky: true
      read_time: true
      comments: true

author:
  name: 王叹之
  bio: 写代码 / 写wp / 记录
  location: 中国

footer:
  links:
    - label: GitHub
      icon: "fab fa-github"
      url: https://github.com/wangtanzhi6
    - label: Email
      icon: "fas fa-envelope"
      url: mailto:your-email@example.com

minimal_mistakes_skin: default

atom_feed:
  hide: false
